"""
Terminology Validation Service.

Loads the ICD-10 and ICD-11 code catalogs (generated by scripts/sync_terminology.py
from the Vulcano IHCE CodeSystems) into memory at startup for O(1) validation.

Usage:
    from app.services.terminology import terminology

    terminology.validate_icd10("A09")     # True
    terminology.validate_icd10("ZZZZZ")   # False
    terminology.get_icd10_display("A09")  # "Diarrea y gastroenteritis..."
"""

import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
ICD10_FILE = DATA_DIR / "icd10_codes.json"
ICD11_FILE = DATA_DIR / "icd11_codes.json"


class TerminologyService:
    """In-memory ICD-10/11 code validation against Vulcano IHCE catalogs."""

    def __init__(self) -> None:
        self._icd10: dict[str, str] = {}
        self._icd11: dict[str, str] = {}
        self._icd10_set: frozenset[str] = frozenset()
        self._icd11_set: frozenset[str] = frozenset()
        self._loaded = False

    def load(self) -> None:
        """Load catalogs from disk. Called once at application startup."""
        self._icd10 = self._load_file(ICD10_FILE, "ICD-10")
        self._icd11 = self._load_file(ICD11_FILE, "ICD-11")
        self._icd10_set = frozenset(self._icd10.keys())
        self._icd11_set = frozenset(self._icd11.keys())
        self._loaded = True
        logger.info(
            "Terminology loaded: %d ICD-10 codes, %d ICD-11 codes",
            len(self._icd10), len(self._icd11),
        )

    @staticmethod
    def _load_file(path: Path, label: str) -> dict[str, str]:
        if not path.exists():
            logger.warning(
                "Terminology file not found: %s — %s validation disabled. "
                "Run 'python scripts/sync_terminology.py' to generate it.",
                path, label,
            )
            return {}
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            logger.info("Loaded %d %s codes from %s", len(data), label, path.name)
            return data
        except (json.JSONDecodeError, OSError) as e:
            logger.error("Failed to load %s catalog from %s: %s", label, path, e)
            return {}

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def icd10_count(self) -> int:
        return len(self._icd10)

    @property
    def icd11_count(self) -> int:
        return len(self._icd11)

    # --- ICD-10 ---

    def validate_icd10(self, code: Optional[str]) -> bool:
        """Check if an ICD-10 code exists in the Vulcano catalog."""
        if not code:
            return False
        if not self._icd10_set:
            # Catalog not loaded — accept all (graceful degradation)
            return True
        return code.strip().upper() in self._icd10_set

    def get_icd10_display(self, code: str) -> Optional[str]:
        """Get the display name for an ICD-10 code, or None if not found."""
        return self._icd10.get(code.strip().upper())

    # --- ICD-11 ---

    def validate_icd11(self, code: Optional[str]) -> bool:
        """Check if an ICD-11 code exists in the Vulcano catalog."""
        if not code:
            return True  # ICD-11 is optional per the IG
        if not self._icd11_set:
            return True  # Catalog not loaded — accept all
        return code.strip() in self._icd11_set

    def get_icd11_display(self, code: str) -> Optional[str]:
        """Get the display name for an ICD-11 code, or None if not found."""
        return self._icd11.get(code.strip())


# Singleton — import this from anywhere in the app
terminology = TerminologyService()
