"""
Terminology Validation Service.

Loads the ICD-10 and ICD-11 code catalogs (generated by scripts/sync_terminology.py
from the WHO ICD API) into memory at startup for O(1) validation.

The catalogs contain the COMPLETE WHO ICD-10 (~12,000 codes) and ICD-11 (~30,000 codes)
downloaded from the official WHO API with Spanish display names.

Usage:
    from app.services.terminology import terminology

    terminology.validate_icd10("B86")     # True — Escabiosis
    terminology.validate_icd10("ZZZZZ")   # False — not a real code
    terminology.get_icd10_display("B86")  # "Escabiosis"
"""

import json
import logging
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
ICD10_FILE = DATA_DIR / "icd10_codes.json"
ICD11_FILE = DATA_DIR / "icd11_codes.json"

# Minimum expected catalog sizes — warns if the loaded catalog is suspiciously small
# (e.g., if someone accidentally loaded the Vulcano fragment instead of the full WHO catalog)
_MIN_ICD10_EXPECTED = 5000
_MIN_ICD11_EXPECTED = 1000

# Format patterns for structural validation as a last resort
_ICD10_PATTERN = re.compile(r"^[A-Z]\d{2,4}$")
_ICD11_PATTERN = re.compile(r"^[A-Z0-9]{2,5}(\.[A-Z0-9]{1,4})?$")


class TerminologyService:
    """
    In-memory ICD-10/11 code validation against the WHO catalogs.

    Validation strategy:
      - If the full catalog is loaded (>5000 ICD-10 codes): exact match.
      - If only a fragment is loaded (<5000 codes): format-based validation
        (to avoid rejecting valid codes that aren't in the fragment).
      - If no catalog is loaded: format-based validation.
    """

    def __init__(self) -> None:
        self._icd10: dict[str, str] = {}
        self._icd11: dict[str, str] = {}
        self._icd10_set: frozenset[str] = frozenset()
        self._icd11_set: frozenset[str] = frozenset()
        self._loaded = False
        self._icd10_full_catalog = False
        self._icd11_full_catalog = False

    def load(self) -> None:
        """Load catalogs from disk. Called once at application startup."""
        self._icd10 = self._load_file(ICD10_FILE, "ICD-10")
        self._icd11 = self._load_file(ICD11_FILE, "ICD-11")
        self._icd10_set = frozenset(self._icd10.keys())
        self._icd11_set = frozenset(self._icd11.keys())
        self._loaded = True

        self._icd10_full_catalog = len(self._icd10) >= _MIN_ICD10_EXPECTED
        self._icd11_full_catalog = len(self._icd11) >= _MIN_ICD11_EXPECTED

        mode_10 = "full catalog" if self._icd10_full_catalog else "fragment"
        mode_11 = "full catalog" if self._icd11_full_catalog else "fragment"
        logger.info(
            "Terminology loaded: %d ICD-10 codes (%s), %d ICD-11 codes (%s)",
            len(self._icd10), mode_10, len(self._icd11), mode_11,
        )

        if not self._icd10_full_catalog and len(self._icd10) > 0:
            logger.warning(
                "ICD-10 catalog has only %d codes (expected >%d). "
                "Using format-based validation. Run 'python scripts/sync_terminology.py' "
                "with WHO API credentials to download the full catalog.",
                len(self._icd10), _MIN_ICD10_EXPECTED,
            )

    @staticmethod
    def _load_file(path: Path, label: str) -> dict[str, str]:
        if not path.exists():
            logger.warning(
                "Terminology file not found: %s — %s validation will use format checks only. "
                "Run 'python scripts/sync_terminology.py' to generate it.",
                path, label,
            )
            return {}
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            logger.info("Loaded %d %s codes from %s", len(data), label, path.name)
            return data
        except (json.JSONDecodeError, OSError) as e:
            logger.error("Failed to load %s catalog from %s: %s", label, path, e)
            return {}

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def icd10_count(self) -> int:
        return len(self._icd10)

    @property
    def icd11_count(self) -> int:
        return len(self._icd11)

    @property
    def has_full_icd10(self) -> bool:
        return self._icd10_full_catalog

    # --- ICD-10 ---

    def validate_icd10(self, code: Optional[str]) -> bool:
        """
        Validate an ICD-10 code.

        - Full catalog loaded (>5000 codes): exact match against WHO catalog.
        - Fragment or no catalog: format-based validation [A-Z]\\d{2,4}.
        """
        if not code:
            return False
        normalized = code.strip().upper()

        if self._icd10_full_catalog:
            # Full catalog — exact match
            return normalized in self._icd10_set

        # Fragment or empty — fall back to format validation
        return bool(_ICD10_PATTERN.match(normalized))

    def get_icd10_display(self, code: str) -> Optional[str]:
        """Get the Spanish display name for an ICD-10 code, or None."""
        return self._icd10.get(code.strip().upper())

    # --- ICD-11 ---

    def validate_icd11(self, code: Optional[str]) -> bool:
        """
        Validate an ICD-11 code. ICD-11 is optional — None/empty always passes.
        """
        if not code:
            return True  # ICD-11 is optional per the IG
        normalized = code.strip()

        if self._icd11_full_catalog:
            return normalized in self._icd11_set

        return bool(_ICD11_PATTERN.match(normalized))

    def get_icd11_display(self, code: str) -> Optional[str]:
        """Get the Spanish display name for an ICD-11 code, or None."""
        return self._icd11.get(code.strip())


# Singleton — import this from anywhere in the app
terminology = TerminologyService()