import uuid
import enum  # stdlib
from sqlalchemy import Column, String, Boolean, DateTime, Date, Text, JSON, Integer, ForeignKey, Enum as SAEnum
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.db.base import Base

class Organization(Base):
    """
    Represents a specific clinical entity (e.g., an NGO or Clinic).
    Serves as the root boundary for the Multi-Tenant architecture.
    """
    __tablename__ = "organizations"
    
    id = Column(String, primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, unique=True, index=True, nullable=False)
    is_active = Column(Boolean, default=True)
    
    # Relationships
    users = relationship("User", back_populates="organization")
    patients = relationship("Patient", back_populates="organization")

class UserRole(str, enum.Enum):
    superadmin = "superadmin"
    org_admin  = "org_admin"
    doctor     = "doctor"
    nurse      = "nurse"
class User(Base):
    """
    System users (Admins, Doctors, Nurses). 
    Strictly bound to an Organization.
    """
    __tablename__ = "users"

    id = Column(String, primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    
    # Foreign Key: Binds user to an organization securely
    organization_id = Column(String, ForeignKey("organizations.id"), nullable=False) 
    
    full_name = Column(String, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    
    # Allowed roles: "superadmin", "org_admin", "doctor", "nurse"
    role = Column(SAEnum(UserRole), nullable=False, default=UserRole.doctor)
    is_active = Column(Boolean, default=True)

    # Relationships
    organization = relationship("Organization", back_populates="users")

class Patient(Base):
    """
    Main Patient Entity.
    Stores relational columns for quick lookups and raw JSON for full clinical history.
    Implements Multi-Tenancy via organization_id.
    
    Relational columns mirror the most-queried RDA elements so the database 
    can filter without scanning JSON. The full_record_json column remains the 
    authoritative source for the complete patient payload.
    """
    __tablename__ = "patients"

    # 1. THE PRIMARY KEY (Generated by Frontend as a UUID v4)
    id = Column(String, primary_key=True, index=True)
    
    # Foreign Key: Binds patient to the organization that registered them
    organization_id = Column(String, ForeignKey("organizations.id"), nullable=False)
    
    # 2. THE HARDWARE ID (NFC Bracelet / Barcode)
    device_uid = Column(String, unique=True, index=True, nullable=False) 

    # --- RDA Identification (Res. 866/2021 Elems. 2.1, 2.2) ---
    document_type = Column(String(5), index=True, nullable=True,
                           comment="Tipo de documento — CC, CE, PA, RC, TI, PT, etc.")
    document_number = Column(String, index=True, nullable=True,
                             comment="Número de documento de identidad del paciente")
    
    # --- Demographics ---
    first_name = Column(String, index=True)
    last_name = Column(String, index=True, comment="Primer apellido (Elem. 3.1)")
    second_last_name = Column(String, nullable=True, comment="Segundo apellido (Elem. 3.2)")
    birth_date = Column(Date)
    biological_sex = Column(String(2), nullable=True, comment="Sexo biológico M/F/I (Elem. 5)")
    blood_type = Column(String(5))

    # --- Nationality (Elems. 1.1, 1.2) — critical for migrant population ---
    nationality_code = Column(String(3), index=True, nullable=True,
                              comment="Código ISO 3166-1 del país de nacionalidad")

    # --- Guardian ---
    guardian_name = Column(String)
    guardian_phone = Column(String)
    
    # --- Raw Full JSON Storage (authoritative clinical payload) ---
    full_record_json = Column(JSON) 
    
    # --- FHIR Sync Tracking ---
    synced_visit_count = Column(
        Integer, default=0, nullable=False, server_default="0",
        comment="Number of medicalHistory visits already sent to FHIR Store"
    )
    rda_paciente_sent = Column(
        Boolean, default=False, nullable=False, server_default="false",
        comment="Whether the RDA-Paciente bundle has been sent at least once"
    )
    
    # Audit Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    organization = relationship("Organization", back_populates="patients")

    def __repr__(self):
        return f"<Patient(id={self.id}, doc={self.document_type}-{self.document_number}, org={self.organization_id})>"

class DiagnosisCIE10(Base):
    __tablename__ = "catalog_cie10"

    code = Column(String(10), primary_key=True, index=True)
    description = Column(Text, nullable=False)
    is_common = Column(Boolean, default=False)

class VaccineCVX(Base):
    __tablename__ = "catalog_vaccines"

    code = Column(String(10), primary_key=True, index=True)
    name = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)