import uuid
from sqlalchemy import Column, String, Boolean, DateTime, Date, Text, JSON, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.db.base import Base

class Organization(Base):
    """
    Represents a specific clinical entity (e.g., an NGO or Clinic).
    Serves as the root boundary for the Multi-Tenant architecture.
    """
    __tablename__ = "organizations"
    
    id = Column(String, primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, unique=True, index=True, nullable=False)
    is_active = Column(Boolean, default=True)
    
    # Relationships
    users = relationship("User", back_populates="organization")
    patients = relationship("Patient", back_populates="organization")

class User(Base):
    """
    System users (Admins, Doctors, Nurses). 
    Strictly bound to an Organization.
    """
    __tablename__ = "users"

    id = Column(String, primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    
    # Foreign Key: Binds user to an organization securely
    organization_id = Column(String, ForeignKey("organizations.id"), nullable=False) 
    
    full_name = Column(String, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    
    # Allowed roles: "superadmin", "org_admin", "doctor", "nurse"
    role = Column(String, default="doctor")
    is_active = Column(Boolean, default=True)

    # Relationships
    organization = relationship("Organization", back_populates="users")

class Patient(Base):
    """
    Main Patient Entity.
    Stores relational data for quick lookups and raw JSON for history.
    Implements Multi-Tenancy via organization_id.
    """
    __tablename__ = "patients"

    # 1. THE PRIMARY KEY (Generated by Frontend as a UUID v4)
    id = Column(String, primary_key=True, index=True)
    
    # Foreign Key: Binds patient to the organization that registered them
    organization_id = Column(String, ForeignKey("organizations.id"), nullable=False)
    
    # 2. THE HARDWARE ID (NFC Bracelet / Barcode)
    device_uid = Column(String, unique=True, index=True, nullable=False) 
    
    # Demographics
    first_name = Column(String, index=True)
    last_name = Column(String, index=True)
    birth_date = Column(Date)
    blood_type = Column(String(5))
    guardian_name = Column(String)
    guardian_phone = Column(String)
    
    # Raw Full JSON Storage (Medical history / FHIR / HL7 payload)
    full_record_json = Column(JSON) 
    
    # Audit Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    organization = relationship("Organization", back_populates="patients")

    def __repr__(self):
        return f"<Patient(id={self.id}, org={self.organization_id})>"

class DiagnosisCIE10(Base):
    __tablename__ = "catalog_cie10"

    code = Column(String(10), primary_key=True, index=True)
    description = Column(Text, nullable=False)
    is_common = Column(Boolean, default=False)

class VaccineCVX(Base):
    __tablename__ = "catalog_vaccines"

    code = Column(String(10), primary_key=True, index=True)
    name = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)