steps:
  # ======================================================
  # PASO 1: EJECUTAR PRUEBAS UNITARIAS (EL ESCUDO)
  # ======================================================
  # Usamos una imagen ligera de Python para correr las pruebas.
  # Si pytest falla, el pipeline se detiene inmediatamente (Fail-Fast).
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install uv
        uv sync
        # Inyectamos variables dummy solo para que la app pase los tests
        export SECRET_KEY="dummy_secret_for_testing_only"
        export DB_PASS="dummy_pass"
        export DATABASE_URL="sqlite:///./test.db"
        export HL7_SENDING_APP="TEST_APP"
        export HL7_PROCESSING_ID="D"
        # ¡Corremos las pruebas!
        uv run pytest

  # ======================================================
  # PASO 2: CONSTRUIR LA IMAGEN DE DOCKER
  # ======================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hwb-backend:$COMMIT_SHA'
      - '.'

  # ======================================================
  # PASO 3: SUBIR LA IMAGEN AL REGISTRY (NUBE)
  # ======================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/hwb-backend:$COMMIT_SHA'

  # ======================================================
  # PASO 4: DESPLEGAR EN CLOUD RUN
  # ======================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hwb-backend-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hwb-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      # Conectamos las variables sensibles con Secret Manager
      - '--update-secrets'
      - 'DB_PASS=hwb-db-pass:latest,SECRET_KEY=hwb-secret-key:latest'

# Tiempo máximo de ejecución del pipeline (15 minutos)
timeout: '900s'

options:
  logging: CLOUD_LOGGING_ONLY