from enum import Enum
from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

class Address(BaseModel):
    street: str
    city: str
    state: str
    zipCode: str
    country: str

class PatientInfo(BaseModel):
    lastName: str
    firstName: str
    dob: date # Date of Birth
    gender: str
    bloodType: str
    address: Address
    weight: Optional[float] = Field(None, description="Weight in Kg (e.g. 12.5)")
    height: Optional[float] = Field(None, description="Height in cm (e.g. 95.0)")

class GuardianInfo(BaseModel):
    name: str
    relationship: str
    phone: str
    device_uid: Optional[str] = Field(None, description="Hardware ID of the guardian's NFC tag")

class BackgroundHistory(BaseModel):
    chronicConditions: Optional[str] = Field(
        default=None, 
        description="Enfermedades crónicas (ej. Asma, Diabetes)."
    )
    personalHistory: Optional[str] = Field(
        default=None, 
        description="Antecedentes personales patológicos, quirúrgicos o de nacimiento."
    )
    familyHistory: Optional[str] = Field(
        default=None, 
        description="Antecedentes familiares de importancia."
    )

class DiagnosisData(BaseModel):
    icd10Code: str
    description: str


class MedicalHistoryItem(BaseModel):
    type: str
    date: date
    location: str
    physician: str
    diagnosis: DiagnosisData
    observations: Optional[str] = None

class VaccinationRecordItem(BaseModel):
    date: date
    vaccineName: str
    vaccineCode: str  # CVX Code
    dose: int
    administratedBy: str
    administratedAt: str
    status: str

class AllergyReactionEnum(str, Enum):
    HABONES = "Habones"
    EDEMA_MUCOSAS = "Edema de mucosas"
    DIFICULTAD_RESPIRAR = "Dificultad para respirar"
    CHOQUE_ANAFILACTICO = "Choque anafiláctico"
    PARO_CARDIACO = "Paro cardiaco"

class AllergyInfo(BaseModel):
    allergen: str
    reaction: AllergyReactionEnum = Field(..., description="tipo de reacción alérgica")
    notes: Optional[str] = None

class ClinicalEvaluation(BaseModel):
    """Datos ingresados manualmente por el médico en el formulario"""
    historyOfCurrentIllness: Optional[str] = Field(None, description="Enfermedad actual: El motivo de consulta de hoy y su evolución.")
    generalPhysicalExamination: Optional[str] = Field(None, description="Examen físico general.")
    systemsExamination: Optional[str] = Field(None, description="Revisión por sistemas.")
    treatmentPlanObservations: Optional[str] = Field(None, description="Plan de tratamiento y observaciones médicas.")

class DiagnosisItem(BaseModel):
    """Diagnóstico estructurado."""
    icd10Code: str
    icd11Code: Optional[str] = None
    description: str

class MedicalHistoryItem(BaseModel):
    """Representa una única visita médica."""
    type: str
    date: date
    location: str
    physician: str
    clinicalEvaluation: ClinicalEvaluation
    diagnosis: List[DiagnosisItem] = []


# --- Main Model (Incoming JSON Payload) ---
class PatientFullRecord(BaseModel):
    patientId: str = Field(..., description="UUID v4 generated by the Frontend application")
    device_uid: str = Field(..., description="Unique identifier from the hardware tag (NFC UID, QR code string, etc.)")
    
    patientInfo: PatientInfo
    guardianInfo: GuardianInfo
    
    # Datos Clínicos Permanentes
    backgroundHistory: Optional[BackgroundHistory] = None
    allergies: List[AllergyInfo] = []
    
    # Datos Episódicos
    medicalHistory: List[MedicalHistoryItem] = []
    vaccinationRecord: List[VaccinationRecordItem] = []

    class Config:
        from_attributes = True

# --- API Responses ---
class PatientSyncResponse(BaseModel):
    status: str
    internal_id: str
    gcp_status: Optional[str] = "unknown"
    message: str