from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

class Address(BaseModel):
    street: str
    city: str
    state: str
    zipCode: str
    country: str

class PatientInfo(BaseModel):
    lastName: str
    firstName: str
    dob: date # Date of Birth
    gender: str
    bloodType: str
    address: Address
    weight: Optional[float] = Field(None, description="Weight in Kg (e.g. 12.5)")
    height: Optional[float] = Field(None, description="Height in cm (e.g. 95.0)")

class GuardianInfo(BaseModel):
    name: str
    relationship: str
    phone: str
    device_uid: Optional[str] = Field(None, description="Hardware ID of the guardian's NFC tag")

class DiagnosisData(BaseModel):
    icd10Code: str
    description: str

class MedicalHistoryItem(BaseModel):
    type: str
    date: date
    location: str
    physician: str
    diagnosis: DiagnosisData
    observations: Optional[str] = None

class VaccinationRecordItem(BaseModel):
    date: date
    vaccineName: str
    vaccineCode: str  # CVX Code
    dose: int
    administratedBy: str
    administratedAt: str
    status: str

class AllergyInfo(BaseModel):
    allergen: str
    icd10Code: str
    reaction: str
    severity: str
    notes: Optional[str] = None

# --- Main Model (Incoming JSON Payload) ---
class PatientFullRecord(BaseModel):
    patientId: str = Field(..., description="UUID v4 generated by the Frontend application")
    device_uid: str = Field(..., description="Unique identifier from the hardware tag (NFC UID, QR code string, etc.)")
    patientInfo: PatientInfo
    guardianInfo: GuardianInfo
    allergies: List[AllergyInfo] = []
    medicalHistory: List[MedicalHistoryItem] = []
    vaccinationRecord: List[VaccinationRecordItem] = []

    class Config:
        from_attributes = True

# --- API Responses ---

class PatientSyncResponse(BaseModel):
    status: str
    internal_id: str
    gcp_status: Optional[str] = "unknown"
    message: str